#' @title Length of Stay (LoS) Forecaster
#' @description Predicts exact hospital Length of Stay (continuous variable) using Base R Regression.
#' Critical for Hospital Bed Management (BPR) and BPJS billing optimization.
#' Integrates strict boundary checks (Zero-crossing CI) for clinical predictor significance.
#' @param data A data.frame containing patient admission profiles and clinical data.
#' @param target_var Character. The name of the continuous outcome variable (e.g., days of stay).
#' @param split_ratio Numeric. Proportion of data for training (default 0.7).
#' @param reverse_palette Logical. If TRUE, reverses the plot color palette.
#' @param save_plot Logical. If TRUE, exports 4K high-resolution plots.
#' @param save_prefix Character. Custom prefix for exported plot filenames.
#' @param footer Logical. If TRUE, adds reproducibility footer to plots.
#' @param seed Numeric. Seed for reproducibility.
#' @return A list containing model summaries, performance metrics (RMSE, MAE, R2), and predictions.
#' @export
#' @examples
#' # Run Model
#' result <- B4_supervised_los(
#'   data = df_B4,
#'   target_var = "los_days",
#'   save_plot = FALSE
#' )
B4_supervised_los <- function(data,
                              target_var,
                              split_ratio = 0.7,
                              reverse_palette = FALSE,
                              save_plot = FALSE,
                              save_prefix = "",
                              footer = TRUE,
                              seed = 42) {

  # 1. Input Validation
  stopifnot("Input 'data' must be a data.frame." = is.data.frame(data))
  stopifnot("Target variable not found in data." = target_var %in% names(data))

  set.seed(seed)

  y <- data[[target_var]]
  if (!is.numeric(y)) {
    stop("Target variable for Length of Stay must be continuous (numeric).")
  }

  # Clean NA from data
  data <- data[stats::complete.cases(data), ]
  n_total <- nrow(data)

  # 2. Train/Test Split (Random Sampling for Continuous Data)
  train_idx <- sample(seq_len(n_total), size = floor(n_total * split_ratio))
  train_data <- data[train_idx, ]
  test_data <- data[-train_idx, ]

  # 3. Modeling (Linear Regression Base R)
  formula_obj <- stats::as.formula(paste(target_var, "~ ."))
  model <- stats::lm(formula_obj, data = train_data)

  # 4. Prediction and Metrics on Unseen Test Data
  test_preds <- stats::predict(model, newdata = test_data)

  # Prevent predicting negative days (Clinical constraint)
  test_preds <- ifelse(test_preds < 0, 0, test_preds)
  actual <- test_data[[target_var]]

  # Calculate Regression Metrics
  residuals <- actual - test_preds
  rmse <- sqrt(mean(residuals^2))
  mae <- mean(abs(residuals))

  # R-squared calculation manually for Test Set
  ss_total <- sum((actual - mean(actual))^2)
  ss_residual <- sum(residuals^2)
  r_squared <- ifelse(ss_total == 0, 0, 1 - (ss_residual / ss_total))

  # 5. Strict Clinical Boundary Check for Coefficients
  coef_vals <- stats::coef(model)[-1] # Remove intercept
  ci_vals <- suppressMessages(stats::confint.default(model))[-1, , drop = FALSE]

  coef_data <- data.frame(
    Predictor = names(coef_vals),
    Estimate = round(coef_vals, 3),
    CI_Lower = round(ci_vals[, 1], 3),
    CI_Upper = round(ci_vals[, 2], 3),
    stringsAsFactors = FALSE
  )

  # Core Logic: If CI crosses 0.00, force label "ns" (Non-Significant)
  coef_data$Significance <- ifelse(coef_data$CI_Lower <= 0 & coef_data$CI_Upper >= 0, "ns", "sig")

  # 6. Visualization Setup
  base_colors <- c("#2C3E50", "#E74C3C", "#18BC9C", "#F39C12") # 2 = Red (Prolong), 3 = Green (Shorten)
  if (reverse_palette) base_colors <- rev(base_colors)
  footer_text <- paste0("Generated by R-Studio (", R.version.string, ") on ", format(Sys.time(), "%B %d, %Y at %H:%M:%S"))

  timestamp_str <- format(Sys.time(), "%Y%m%d_%H%M%S")

  # ==========================================
  # PLOT 1: Topology & Prediction Map
  # ==========================================
  graphics::par(mar = c(8, 5, 4, 2) + 0.1, mfrow = c(1, 2))

  # Subplot 1A: Distribution Map
  dens_act <- stats::density(actual)
  dens_pred <- stats::density(test_preds)

  x_max <- max(c(dens_act$x, dens_pred$x))
  y_max <- max(c(dens_act$y, dens_pred$y))

  graphics::plot(dens_act, main = "LoS Distribution Profile",
                 xlab = "", ylab = "Density", col = base_colors[1], lwd = 2,
                 xlim = c(0, x_max), ylim = c(0, y_max * 1.1), bty = "n")
  graphics::polygon(dens_act, col = grDevices::adjustcolor(base_colors[1], alpha.f = 0.3), border = NA)
  graphics::lines(dens_pred, col = base_colors[4], lwd = 2, lty = 2)
  graphics::polygon(dens_pred, col = grDevices::adjustcolor(base_colors[4], alpha.f = 0.2), border = NA)

  graphics::legend("bottom", legend = c("Actual LoS", "Predicted LoS"),
                   fill = c(grDevices::adjustcolor(base_colors[1], alpha.f = 0.3),
                            grDevices::adjustcolor(base_colors[4], alpha.f = 0.2)),
                   bty = "n", horiz = TRUE, inset = c(0, -0.3), xpd = TRUE, cex = 1)

  # Subplot 1B: Actual vs Predicted Scatter
  graphics::plot(actual, test_preds, pch = 16, col = grDevices::adjustcolor(base_colors[1], alpha.f = 0.6),
                 main = "Actual vs Predicted Days",
                 xlab = "", ylab = "Predicted Length of Stay (Days)",
                 xlim = c(0, max(actual, test_preds)), ylim = c(0, max(actual, test_preds)), bty = "n")

  graphics::abline(a = 0, b = 1, col = base_colors[2], lwd = 2, lty = 2)
  fit_line <- stats::lm(test_preds ~ actual)
  graphics::abline(fit_line, col = base_colors[3], lwd = 2)

  graphics::legend("bottom", legend = c("Ideal Match (1:1)", "Model Trend"),
                   col = base_colors[2:3], lty = c(2, 1), lwd = 2,
                   bty = "n", horiz = TRUE, inset = c(0, -0.3), xpd = TRUE, cex = 1)

  if (footer) graphics::mtext(footer_text, side = 1, line = 6.5, adj = 0, cex = 0.7, col = "grey40", outer = FALSE)

  if (save_plot) {
    file_name1 <- paste0("B4_Topology_", timestamp_str, "_", save_prefix, ".png")
    grDevices::dev.copy(grDevices::png, filename = file_name1, width = 3840, height = 2160, res = 300)
    grDevices::dev.off()
    message("Saved: ", file_name1)
  }

  # ==========================================
  # PLOT 2: Diagnostic Performance (Residuals & Forest)
  # ==========================================
  graphics::par(mfrow = c(1, 2), mar = c(7, 4, 4, 2) + 0.1)

  # Subplot 2A: Residuals vs Fitted
  graphics::plot(test_preds, residuals, pch = 16, col = grDevices::adjustcolor(base_colors[1], alpha.f = 0.5),
                 main = "Residual Diagnostics",
                 xlab = "Fitted Values (Predicted Days)", ylab = "Residuals (Error in Days)",
                 bty = "n")
  graphics::abline(h = 0, col = "grey50", lty = 2, lwd = 2)

  smooth_res <- stats::smooth.spline(test_preds, residuals, df = 4)
  graphics::lines(smooth_res, col = base_colors[2], lwd = 2)

  metrics_txt <- sprintf("RMSE: %.2f Days\nMAE: %.2f Days\nR-Squared: %.2f", rmse, mae, r_squared)
  graphics::legend("bottomright", legend = metrics_txt, bty = "n", text.col = "black", cex = 0.9)

  # Subplot 2B: Directional Clinical Boundary Forest Plot (Linear)
  n_vars <- nrow(coef_data)
  y_pos <- n_vars:1

  point_colors <- ifelse(coef_data$Significance == "ns", "#B0B0B0",
                         ifelse(coef_data$Estimate > 0, base_colors[2], base_colors[3]))
  font_weights <- ifelse(coef_data$Significance == "ns", 1, 2)

  # SPATIAL ALIGNMENT REWORK: Dynamic Padding Calculation to prevent overlap
  x_range <- max(coef_data$CI_Upper) - min(coef_data$CI_Lower)
  if (x_range == 0) x_range <- 1 # Failsafe

  # Provide 60% padding on the left for text, 50% on the right for values
  x_min_plot <- min(min(coef_data$CI_Lower), 0) - (x_range * 0.6)
  x_max_plot <- max(max(coef_data$CI_Upper), 0) + (x_range * 0.5)

  graphics::plot(coef_data$Estimate, y_pos, pch = 16, cex = 1.5, col = point_colors,
                 xlim = c(x_min_plot, x_max_plot),
                 ylim = c(0.5, n_vars + 1),
                 yaxt = "n", xlab = "Estimate Effect on LoS (Days)", ylab = "",
                 main = "Predictor Impacts\n(Directional Zero-Boundary)",
                 bty = "n")
  graphics::abline(v = 0.0, lty = 2, col = "black", lwd = 1.5)

  # Draw directional error bars and text labels using Pillar Alignment
  for (i in 1:n_vars) {
    graphics::segments(x0 = coef_data$CI_Lower[i], y0 = y_pos[i],
                       x1 = coef_data$CI_Upper[i], y1 = y_pos[i],
                       col = point_colors[i], lwd = 2)

    # Left Label (Predictor Name) - Strictly Left-Aligned (pos = 4 starts from coordinate going right)
    graphics::text(x = x_min_plot, y = y_pos[i],
                   labels = coef_data$Predictor[i], pos = 4, xpd = TRUE,
                   col = point_colors[i], font = font_weights[i], cex = 0.9)

    # Right Label (Value String) - Strictly Right-Aligned (pos = 2 starts from coordinate going left)
    graphics::text(x = x_max_plot, y = y_pos[i],
                   labels = sprintf("%.2f [%.2f, %.2f]", coef_data$Estimate[i], coef_data$CI_Lower[i], coef_data$CI_Upper[i]),
                   pos = 2, cex = 0.8, col = point_colors[i], xpd = TRUE)
  }

  if (footer) graphics::mtext(footer_text, side = 1, line = 5.5, adj = 0.5, cex = 0.7, col = "grey40")

  if (save_plot) {
    file_name2 <- paste0("B4_Diagnostics_", timestamp_str, "_", save_prefix, ".png")
    grDevices::dev.copy(grDevices::png, filename = file_name2, width = 3840, height = 2160, res = 300)
    grDevices::dev.off()
    message("Saved: ", file_name2)
  }

  graphics::par(mfrow = c(1, 1), mar = c(5, 4, 4, 2) + 0.1)

  # 7. Return Objects
  results <- list(
    Metrics = data.frame(
      RMSE = rmse,
      MAE = mae,
      R_Squared = r_squared
    ),
    Strict_Coef_Table = coef_data,
    Model = model
  )

  return(invisible(results))
}
