#' @title Precision Dosage Predictor (Pharmacogenomics Forecaster)
#' @description Computational regression engine to predict exact personalized dosage
#' for narrow therapeutic index drugs (e.g., Warfarin, Insulin).
#' Integrates Absolute Zero failsafe (prevents negative dose prediction) and
#' Pillar-Aligned Forest Plot with strict Zero-Boundary clinical checks.
#' @param data A data.frame containing patient biometrics, lab results, and genetic markers.
#' @param target_var Character. The name of the continuous outcome variable (e.g., weekly_dose_mg).
#' @param split_ratio Numeric. Proportion of data for training (default 0.7).
#' @param reverse_palette Logical. If TRUE, reverses the plot color palette.
#' @param save_plot Logical. If TRUE, exports 4K high-resolution plots.
#' @param save_prefix Character. Custom prefix for exported plot filenames.
#' @param footer Logical. If TRUE, adds reproducibility footer to plots.
#' @param seed Numeric. Seed for reproducibility.
#' @return A list containing model summaries, precision metrics (RMSE, MAE, R2), and coefficients.
#' @export
#' @examples
#' # Run Model
#' result <- B6_supervised_precision(
#'   data = df_B6,
#'   target_var = "weekly_dose_mg",
#'   save_plot = FALSE
#' )
B6_supervised_precision <- function(data,
                                    target_var,
                                    split_ratio = 0.7,
                                    reverse_palette = FALSE,
                                    save_plot = FALSE,
                                    save_prefix = "",
                                    footer = TRUE,
                                    seed = 42) {

  # 1. Input Validation
  stopifnot("Input 'data' must be a data.frame." = is.data.frame(data))
  stopifnot("Target variable not found in data." = target_var %in% names(data))

  set.seed(seed)

  y <- data[[target_var]]
  if (!is.numeric(y)) {
    stop("Target variable for dosage must be continuous (numeric).")
  }
  if (any(stats::na.omit(y) < 0)) {
    warning("Target variable contains negative doses. Proceeding, but ideally doses should be >= 0.")
  }

  data <- data[stats::complete.cases(data), ]
  n_total <- nrow(data)

  # 2. Train/Test Split
  train_idx <- sample(seq_len(n_total), size = floor(n_total * split_ratio))
  train_data <- data[train_idx, ]
  test_data <- data[-train_idx, ]

  # 3. Precision Modeling (Linear Regression Base R)
  formula_obj <- stats::as.formula(paste(target_var, "~ ."))
  model <- stats::lm(formula_obj, data = train_data)

  # 4. Exact Dosage Prediction
  test_preds <- stats::predict(model, newdata = test_data)

  # CLINICAL FAILSAFE: Prevent Machine from recommending negative dosage
  test_preds <- ifelse(test_preds < 0, 0, test_preds)
  actual <- test_data[[target_var]]

  # Calculate Regression Metrics
  residuals <- actual - test_preds
  rmse <- sqrt(mean(residuals^2))
  mae <- mean(abs(residuals))

  ss_total <- sum((actual - mean(actual))^2)
  ss_residual <- sum(residuals^2)
  r_squared <- ifelse(ss_total == 0, 0, 1 - (ss_residual / ss_total))

  # 5. Strict Clinical Boundary Check
  coef_vals <- stats::coef(model)[-1]
  ci_vals <- suppressMessages(stats::confint.default(model))[-1, , drop = FALSE]

  coef_data <- data.frame(
    Predictor = names(coef_vals),
    Estimate = round(coef_vals, 3),
    CI_Lower = round(ci_vals[, 1], 3),
    CI_Upper = round(ci_vals[, 2], 3),
    stringsAsFactors = FALSE
  )

  # Zero-Boundary logic for Pharmacokinetics
  coef_data$Significance <- ifelse(coef_data$CI_Lower <= 0 & coef_data$CI_Upper >= 0, "ns", "sig")

  # 6. Visualization Setup
  # 2 = Red (Increases Dose Requirement), 3 = Green (Decreases Dose Requirement)
  base_colors <- c("#2C3E50", "#E74C3C", "#18BC9C", "#F39C12")
  if (reverse_palette) base_colors <- rev(base_colors)
  footer_text <- paste0("Generated by R-Studio (", R.version.string, ") on ", format(Sys.time(), "%B %d, %Y at %H:%M:%S"))

  timestamp_str <- format(Sys.time(), "%Y%m%d_%H%M%S")

  # ==========================================
  # PLOT 1: Dosage Topology & Prescribing Map
  # ==========================================
  graphics::par(mar = c(8, 5, 4, 2) + 0.1, mfrow = c(1, 2))

  # Subplot 1A: Dosage Distribution Profile
  dens_act <- stats::density(actual)
  dens_pred <- stats::density(test_preds)

  x_max <- max(c(dens_act$x, dens_pred$x))
  y_max <- max(c(dens_act$y, dens_pred$y))

  graphics::plot(dens_act, main = "Dosage Requirement Distribution",
                 xlab = "", ylab = "Patient Density", col = base_colors[1], lwd = 2,
                 xlim = c(0, x_max), ylim = c(0, y_max * 1.2), bty = "n")
  graphics::polygon(dens_act, col = grDevices::adjustcolor(base_colors[1], alpha.f = 0.3), border = NA)
  graphics::lines(dens_pred, col = base_colors[4], lwd = 2, lty = 2)
  graphics::polygon(dens_pred, col = grDevices::adjustcolor(base_colors[4], alpha.f = 0.2), border = NA)

  graphics::legend("bottom", legend = c("Actual Dosage", "AI Prediction"),
                   fill = c(grDevices::adjustcolor(base_colors[1], alpha.f = 0.3),
                            grDevices::adjustcolor(base_colors[4], alpha.f = 0.2)),
                   bty = "n", horiz = TRUE, inset = c(0, -0.3), xpd = TRUE, cex = 1)

  # Subplot 1B: Actual vs Predicted Scatter
  graphics::plot(actual, test_preds, pch = 16, col = grDevices::adjustcolor(base_colors[1], alpha.f = 0.6),
                 main = "Dosage Precision: Actual vs AI",
                 xlab = "", ylab = "Predicted Dosage (mg/unit)",
                 xlim = c(0, max(actual, test_preds)), ylim = c(0, max(actual, test_preds)), bty = "n")

  graphics::abline(a = 0, b = 1, col = base_colors[2], lwd = 2, lty = 2)
  fit_line <- stats::lm(test_preds ~ actual)
  graphics::abline(fit_line, col = base_colors[3], lwd = 2)

  graphics::legend("bottom", legend = c("Ideal (Perfect Match)", "Prediction Trend"),
                   col = base_colors[2:3], lty = c(2, 1), lwd = 2,
                   bty = "n", horiz = TRUE, inset = c(0, -0.3), xpd = TRUE, cex = 1)

  if (footer) graphics::mtext(footer_text, side = 1, line = 6.5, adj = 0, cex = 0.7, col = "grey40", outer = FALSE)

  if (save_plot) {
    file_name1 <- paste0("B6_Topology_", timestamp_str, "_", save_prefix, ".png")
    grDevices::dev.copy(grDevices::png, filename = file_name1, width = 3840, height = 2160, res = 300)
    grDevices::dev.off()
    message("Saved: ", file_name1)
  }

  # ==========================================
  # PLOT 2: Diagnostic Performance & Pharmacogenomic Forest
  # ==========================================
  graphics::par(mfrow = c(1, 2), mar = c(7, 4, 4, 2) + 0.1)

  # Subplot 2A: Error Diagnostics (Residuals vs Fitted)
  graphics::plot(test_preds, residuals, pch = 16, col = grDevices::adjustcolor(base_colors[1], alpha.f = 0.5),
                 main = "Clinical Error Diagnostics",
                 xlab = "AI Dosage Recommendation (mg/unit)", ylab = "Residuals (Dose Difference)",
                 bty = "n")
  graphics::abline(h = 0, col = "grey50", lty = 2, lwd = 2)

  smooth_res <- stats::smooth.spline(test_preds, residuals, df = 4)
  graphics::lines(smooth_res, col = base_colors[2], lwd = 2)

  metrics_txt <- sprintf("RMSE: %.2f Units\nMAE: %.2f Units\nR-Squared: %.2f", rmse, mae, r_squared)
  graphics::legend("bottomright", legend = metrics_txt, bty = "n", text.col = "black", cex = 0.9)

  # Subplot 2B: Pillar-Aligned Forest Plot (Directional Dose Adjustment)
  n_vars <- nrow(coef_data)
  y_pos <- n_vars:1

  point_colors <- ifelse(coef_data$Significance == "ns", "#B0B0B0",
                         ifelse(coef_data$Estimate > 0, base_colors[2], base_colors[3]))
  font_weights <- ifelse(coef_data$Significance == "ns", 1, 2)

  # PILLAR ALIGNMENT ALGORITHM
  x_range <- max(coef_data$CI_Upper) - min(coef_data$CI_Lower)
  if (x_range == 0) x_range <- 1

  # 60% Left Padding for Names, 50% Right Padding for Values
  x_min_plot <- min(min(coef_data$CI_Lower), 0) - (x_range * 0.6)
  x_max_plot <- max(max(coef_data$CI_Upper), 0) + (x_range * 0.5)

  graphics::plot(coef_data$Estimate, y_pos, pch = 16, cex = 1.5, col = point_colors,
                 xlim = c(x_min_plot, x_max_plot), ylim = c(0.5, n_vars + 1),
                 yaxt = "n", xlab = "Estimated Dose Adjustment", ylab = "",
                 main = "Pharmacogenomic Impacts\n(Pillar-Aligned Adjustment)", bty = "n")
  graphics::abline(v = 0.0, lty = 2, col = "black", lwd = 1.5)

  # Render Pillar-Aligned Elements
  for (i in 1:n_vars) {
    graphics::segments(x0 = coef_data$CI_Lower[i], y0 = y_pos[i],
                       x1 = coef_data$CI_Upper[i], y1 = y_pos[i],
                       col = point_colors[i], lwd = 2)

    # Pillar 1: Variabel Ekstrim Kiri (pos = 4)
    graphics::text(x = x_min_plot, y = y_pos[i],
                   labels = coef_data$Predictor[i], pos = 4, xpd = TRUE,
                   col = point_colors[i], font = font_weights[i], cex = 0.9)

    # Pillar 2: Value Ekstrim Kanan (pos = 2)
    graphics::text(x = x_max_plot, y = y_pos[i],
                   labels = sprintf("%.2f [%.2f, %.2f]", coef_data$Estimate[i], coef_data$CI_Lower[i], coef_data$CI_Upper[i]),
                   pos = 2, cex = 0.8, col = point_colors[i], xpd = TRUE)
  }

  if (footer) graphics::mtext(footer_text, side = 1, line = 5.5, adj = 0, cex = 0.7, col = "grey40")

  if (save_plot) {
    file_name2 <- paste0("B6_Diagnostics_", timestamp_str, "_", save_prefix, ".png")
    grDevices::dev.copy(grDevices::png, filename = file_name2, width = 3840, height = 2160, res = 300)
    grDevices::dev.off()
    message("Saved: ", file_name2)
  }

  graphics::par(mfrow = c(1, 1), mar = c(5, 4, 4, 2) + 0.1)

  # 7. Return Objects
  results <- list(
    Metrics = data.frame(
      RMSE = rmse,
      MAE = mae,
      R_Squared = r_squared
    ),
    Strict_Coef_Table = coef_data,
    Model = model
  )

  return(invisible(results))
}
