#' @title Black-Box AI Explainer (Local Feature Contribution / SHAP Alternative)
#' @description Zero-dependency Explainable AI (XAI) engine. Generates two 4K clinical layouts:
#' Plot 1: AI Explainability (Global Feature Impact vs Local Patient Tornado Chart).
#' Plot 2: Clinical Patient Profile (Biometric Radar vs Cumulative Risk Waterfall Chart).
#' Restores clinical accountability by mathematically explaining AI predictions.
#' @param data A data.frame containing clinical predictors.
#' @param target_var Character. The name of the binary outcome variable (0 = Survival, 1 = Fatal Event).
#' @param patient_index Numeric. The row index of the specific patient to analyze (default is 1).
#' @param reverse_palette Logical. If TRUE, reverses the plot color palette.
#' @param save_plot Logical. If TRUE, exports two separate 4K high-resolution plots.
#' @param save_prefix Character. Custom prefix for exported plot filenames.
#' @param footer Logical. If TRUE, adds reproducibility footer to plots.
#' @param seed Numeric. Seed for reproducibility.
#' @return A list containing Global Feature Importance, Local Contributions, and the Model.
#' @export
#' @examples
#' # Run Explainer for Patient #1
#' result <- B9_supervised_explain(
#'   data = df_B9,
#'   target_var = "shock_event",
#'   patient_index = 1,
#'   save_plot = FALSE
#' )
B9_supervised_explain <- function(data,
                                  target_var,
                                  patient_index = 1,
                                  reverse_palette = FALSE,
                                  save_plot = FALSE,
                                  save_prefix = "",
                                  footer = TRUE,
                                  seed = 42) {

  # 1. Input Validation & Preparation
  stopifnot("Input 'data' must be a data.frame." = is.data.frame(data))
  stopifnot("Target variable not found in data." = target_var %in% names(data))

  set.seed(seed)
  y <- data[[target_var]]
  if (!is.numeric(y) || length(unique(stats::na.omit(y))) != 2) {
    stop("Target variable must be binary (numeric 0 and 1).")
  }
  if (patient_index < 1 || patient_index > nrow(data)) {
    stop(paste("Patient index out of bounds. Must be between 1 and", nrow(data)))
  }

  patient_raw_data <- data[patient_index, , drop = FALSE]
  if (any(is.na(patient_raw_data))) stop("Selected patient has NA values.")

  data_clean <- data[stats::complete.cases(data), ]

  # 2. Train Core AI Model
  formula_obj <- stats::as.formula(paste(target_var, "~ ."))
  model <- suppressWarnings(stats::glm(formula_obj, data = data_clean, family = stats::binomial(link = "logit")))

  # 3. Base R XAI Engine (Math Core)
  coef_vals <- stats::coef(model)[-1]
  intercept <- stats::coef(model)[1]
  features_only <- data_clean[, names(coef_vals), drop = FALSE]

  mean_features <- colMeans(features_only)
  sd_features <- apply(features_only, 2, stats::sd)
  baseline_log_odds <- intercept + sum(coef_vals * mean_features)
  baseline_prob <- 1 / (1 + exp(-baseline_log_odds))

  features_centered <- t(apply(features_only, 1, function(row) row - mean_features))
  contribution_matrix <- t(t(features_centered) * coef_vals)
  colnames(contribution_matrix) <- names(coef_vals)

  # 4. Global Importance Calculation
  global_importance <- colMeans(abs(contribution_matrix))
  global_importance <- sort(global_importance, decreasing = FALSE)

  # 5. Local Explainability Calculation (Specific Patient)
  patient_clean_idx <- which(rownames(data_clean) == rownames(data)[patient_index])
  if(length(patient_clean_idx) == 0) stop("Patient lost during NA cleaning.")

  patient_contrib <- contribution_matrix[patient_clean_idx, ]
  patient_values <- features_only[patient_clean_idx, ]

  pat_log_odds <- intercept + sum(coef_vals * patient_values)
  pat_prob <- 1 / (1 + exp(-pat_log_odds))

  # For Tornado Chart (Sorted by absolute magnitude)
  sort_idx_tornado <- order(abs(patient_contrib), decreasing = FALSE)
  pat_contrib_tornado <- patient_contrib[sort_idx_tornado]
  pat_values_tornado <- patient_values[sort_idx_tornado]
  pat_names_tornado <- names(pat_contrib_tornado)

  # For Waterfall Chart
  sort_idx_waterfall <- order(abs(patient_contrib), decreasing = TRUE)
  contrib_wf <- patient_contrib[sort_idx_waterfall]
  names_wf <- names(contrib_wf)

  # 6. Visualization Settings
  base_colors <- c("#95A5A6", "#E74C3C", "#18BC9C", "#2C3E50", "#F39C12")
  if (reverse_palette) base_colors <- rev(base_colors)
  footer_text <- paste0("Generated by R-Studio (", R.version.string, ") on ", format(Sys.time(), "%B %d, %Y at %H:%M:%S"))
  timestamp_str <- format(Sys.time(), "%Y%m%d_%H%M%S")

  # ==========================================
  # PLOT 1: AI EXPLAINABILITY (Global vs Local)
  # ==========================================
  # Extra bottom margin (9) to prevent X-label and Legend collision
  graphics::par(mfrow = c(1, 2), mar = c(9, 5, 5, 2) + 0.1, oma = c(4, 0, 0, 0))

  # --- Subplot 1A: Global Feature Importance ---
  bp <- graphics::barplot(global_importance, horiz = TRUE, col = base_colors[4], border = NA,
                          main = "Global Explainability:\nMean Absolute Feature Impact",
                          xlab = "Average Contribution to Risk Prediction (Log-Odds)",
                          las = 1, cex.names = 0.8, xlim = c(0, max(global_importance) * 1.4))

  graphics::text(x = global_importance, y = bp, labels = round(global_importance, 3),
                 pos = 4, cex = 0.8, col = "black")

  # FIX 1: Relocated Baseline text far below the x-axis to prevent bar collision
  baseline_txt <- sprintf("Population Baseline Risk: %.1f%%", baseline_prob * 100)
  graphics::legend("bottom", legend = baseline_txt, bty = "n", cex = 0.9, text.col = "black",
                   inset = c(0, -0.5), xpd = TRUE)

  # --- Subplot 1B: Local Explainability (Tornado Chart) ---
  n_vars <- length(pat_contrib_tornado)
  y_pos <- 1:n_vars

  point_colors <- ifelse(pat_contrib_tornado > 0, base_colors[2], base_colors[3])

  x_range <- max(pat_contrib_tornado) - min(pat_contrib_tornado)
  if (x_range == 0) x_range <- 1

  x_min_plot <- min(min(pat_contrib_tornado), 0) - (x_range * 0.9)
  x_max_plot <- max(max(pat_contrib_tornado), 0) + (x_range * 0.9)

  pat_title <- sprintf("Local Explainability (Patient #%d)\nAI Predicted Risk: %.1f%%", patient_index, pat_prob * 100)

  graphics::plot(pat_contrib_tornado, y_pos, pch = 16, cex = 1.5, col = point_colors,
                 xlim = c(x_min_plot, x_max_plot), ylim = c(0.5, n_vars + 1),
                 yaxt = "n", xlab = "Feature Contribution to Patient Risk (Shift from Baseline)", ylab = "",
                 main = pat_title, bty = "n")
  graphics::abline(v = 0.0, lty = 2, col = "black", lwd = 1.5)

  for (i in 1:n_vars) {
    graphics::segments(x0 = 0, y0 = y_pos[i],
                       x1 = pat_contrib_tornado[i], y1 = y_pos[i],
                       col = point_colors[i], lwd = 6)

    graphics::text(x = x_min_plot, y = y_pos[i],
                   labels = pat_names_tornado[i], pos = 4, xpd = TRUE,
                   col = "black", font = 2, cex = 0.9)

    sign_str <- ifelse(pat_contrib_tornado[i] > 0, "+", "")
    effect_str <- sprintf("Value: %.2f (Effect: %s%.2f)", pat_values_tornado[1, i], sign_str, pat_contrib_tornado[i])

    graphics::text(x = x_max_plot, y = y_pos[i],
                   labels = effect_str,
                   pos = 2, cex = 0.85, col = point_colors[i], font = 2, xpd = TRUE)
  }

  # FIX 2: Increased inset to push legend further down, avoiding X-axis label collision
  graphics::legend("bottom", legend = c("Increases Fatal Risk", "Decreases Fatal Risk"),
                   fill = c(base_colors[2], base_colors[3]), bty = "n",
                   horiz = TRUE, inset = c(0.2, -.5), xpd = TRUE, cex = 0.9)

  # Footer Plot 1
  if (footer) graphics::mtext(footer_text, side = 1, line = 2, outer = TRUE, adj = 0.5, cex = 0.7, col = "grey40")

  if (save_plot) {
    file_name1 <- paste0("B9_Plot1_Explainability_", timestamp_str, "_", save_prefix, ".png")
    grDevices::dev.copy(grDevices::png, filename = file_name1, width = 3840, height = 2160, res = 300)
    grDevices::dev.off()
    message("Saved Plot 1: ", file_name1)
  }

  # ==========================================
  # PLOT 2: CLINICAL PATIENT PROFILE (Radar vs Waterfall)
  # ==========================================
  if (!save_plot) grDevices::dev.new()
  graphics::par(mfrow = c(1, 2), mar = c(9, 5, 5, 2) + 0.1, oma = c(4, 0, 0, 0))

  # --- Subplot 2A: Clinical Radar Profile ---
  z_scores <- (patient_values - mean_features) / (sd_features + 1e-6)
  z_scores[z_scores > 3] <- 3
  z_scores[z_scores < -3] <- -3

  n_rad <- length(z_scores)
  angles <- seq(0, 2 * pi, length.out = n_rad + 1)

  # FIX 3: Expanded canvas limits from c(-3.5, 3.5) to c(-5, 5) to prevent cropped text at the edges
  graphics::plot(0, 0, type = "n", xlim = c(-5, 5), ylim = c(-5, 5),
                 axes = FALSE, xlab = "", ylab = "",
                 main = sprintf("Patient Biometric Radar Profile\n(Standardized Z-Score from Mean)"))

  for (r in 1:3) {
    x_circ <- r * cos(seq(0, 2 * pi, length.out = 100))
    y_circ <- r * sin(seq(0, 2 * pi, length.out = 100))
    graphics::lines(x_circ, y_circ, col = "grey80", lty = 2)
    graphics::text(0, r, labels = paste0(r, " SD"), cex = 0.6, col = "grey50", pos = 3)
  }

  for (i in 1:n_rad) {
    graphics::segments(0, 0, 3.5 * cos(angles[i]), 3.5 * sin(angles[i]), col = "grey80")
    adj_x <- ifelse(cos(angles[i]) < 0, 1, 0)
    # Pushed labels slightly further out (3.9) in the expanded canvas
    graphics::text(3.9 * cos(angles[i]), 3.9 * sin(angles[i]), labels = names(z_scores)[i],
                   cex = 0.8, font = 2, adj = c(adj_x, 0.5))
  }

  x_pat <- as.numeric(z_scores) * cos(angles[1:n_rad])
  y_pat <- as.numeric(z_scores) * sin(angles[1:n_rad])
  x_pat <- c(x_pat, x_pat[1])
  y_pat <- c(y_pat, y_pat[1])

  graphics::polygon(x_pat, y_pat, col = grDevices::adjustcolor(base_colors[4], alpha.f = 0.3),
                    border = base_colors[4], lwd = 2)
  graphics::points(x_pat, y_pat, pch = 16, col = base_colors[4])

  # --- Subplot 2B: Cumulative Risk Waterfall Chart ---
  wf_starts <- c(0, baseline_log_odds, baseline_log_odds + cumsum(contrib_wf)[-length(contrib_wf)])
  wf_ends <- c(baseline_log_odds, baseline_log_odds + cumsum(contrib_wf))
  wf_ends <- c(wf_ends, pat_log_odds)
  wf_starts <- c(wf_starts, 0)

  wf_names <- c("Baseline Risk", names_wf, "Final Prediction")
  wf_colors <- c(base_colors[1], ifelse(contrib_wf > 0, base_colors[2], base_colors[3]), base_colors[4])

  y_min_wf <- min(c(wf_starts, wf_ends, 0)) - 1
  y_max_wf <- max(c(wf_starts, wf_ends)) + 1

  graphics::plot(1:(n_vars + 2), wf_ends, type = "n",
                 xlim = c(0.5, n_vars + 2.5), ylim = c(y_min_wf, y_max_wf),
                 xaxt = "n", xlab = "", ylab = "Cumulative Log-Odds",
                 main = "Cumulative Risk Trajectory (Waterfall Chart)", bty = "n")
  graphics::abline(h = 0, lty = 2, col = "grey60")

  for (i in 1:(n_vars + 2)) {
    graphics::rect(xleft = i - 0.4, ybottom = wf_starts[i],
                   xright = i + 0.4, ytop = wf_ends[i],
                   col = wf_colors[i], border = NA)

    lbl_val <- wf_ends[i] - wf_starts[i]
    sign_lbl <- ifelse(lbl_val > 0 && i > 1 && i < (n_vars + 2), "+", "")
    graphics::text(x = i, y = max(wf_starts[i], wf_ends[i]) + 0.2,
                   labels = sprintf("%s%.2f", sign_lbl, lbl_val),
                   cex = 0.75, font = 2, col = "black")

    if (i < (n_vars + 2)) {
      graphics::segments(x0 = i - 0.4, y0 = wf_ends[i], x1 = i + 1.4, y1 = wf_ends[i],
                         col = "grey50", lty = 3)
    }
  }

  graphics::axis(1, at = 1:(n_vars + 2), labels = wf_names, las = 2, cex.axis = 0.8)

  # Footer Plot 2
  if (footer) graphics::mtext(footer_text, side = 1, line = 2, outer = TRUE, adj = 0.5, cex = 0.7, col = "grey40")

  if (save_plot) {
    file_name2 <- paste0("B9_Plot2_ClinicalProfile_", timestamp_str, "_", save_prefix, ".png")
    grDevices::dev.copy(grDevices::png, filename = file_name2, width = 3840, height = 2160, res = 300)
    grDevices::dev.off()
    message("Saved Plot 2: ", file_name2)
  }

  # Reset Par
  graphics::par(mfrow = c(1, 1), mar = c(5, 4, 4, 2) + 0.1, oma = c(0, 0, 0, 0))

  # 7. Return Object
  results <- list(
    Patient_Index = patient_index,
    Predicted_Probability = pat_prob,
    Global_Importance = global_importance,
    Local_Contributions = pat_contrib_tornado,
    Model = model
  )

  return(invisible(results))
}
